name: factory_castle_flutter
description: A complete MVVM state management solution for Flutter based on factory_castle package.
version: 3.1.0
repository: https://github.com/nuc134r/factory_castle

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  factory_castle: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter