name: factory_castle_flutter
description: A complete MVVM state management solution for Flutter based on factory_castle package.
version: 2.0.0
repository: https://github.com/nuc134r/factory_castle_flutter

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  factory_castle: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter