name: factory_castle
description: An IoC container for Dart inspired by Castle Windsor
version: 1.0.0
repository: https://github.com/nuc134r/factory_castle

environment:
  sdk: ">=2.7.0 <3.0.0"

dev_dependencies:
  test: ^1.15.5